// Code generated by "enumer -type=launcherMode,settingsActionGroup,mediaView -linecomment -json -text -output app_enums.go"; DO NOT EDIT.

package app

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _launcherModeName = "browsepassword"

var _launcherModeIndex = [...]uint8{0, 6, 14}

const _launcherModeLowerName = "browsepassword"

func (i launcherMode) String() string {
	if i >= launcherMode(len(_launcherModeIndex)-1) {
		return fmt.Sprintf("launcherMode(%d)", i)
	}
	return _launcherModeName[_launcherModeIndex[i]:_launcherModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _launcherModeNoOp() {
	var x [1]struct{}
	_ = x[launcherModeBrowse-(0)]
	_ = x[launcherModePassword-(1)]
}

var _launcherModeValues = []launcherMode{launcherModeBrowse, launcherModePassword}

var _launcherModeNameToValueMap = map[string]launcherMode{
	_launcherModeName[0:6]:       launcherModeBrowse,
	_launcherModeLowerName[0:6]:  launcherModeBrowse,
	_launcherModeName[6:14]:      launcherModePassword,
	_launcherModeLowerName[6:14]: launcherModePassword,
}

var _launcherModeNames = []string{
	_launcherModeName[0:6],
	_launcherModeName[6:14],
}

// launcherModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func launcherModeString(s string) (launcherMode, error) {
	if val, ok := _launcherModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _launcherModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to launcherMode values", s)
}

// launcherModeValues returns all values of the enum
func launcherModeValues() []launcherMode {
	return _launcherModeValues
}

// launcherModeStrings returns a slice of all String values of the enum
func launcherModeStrings() []string {
	strs := make([]string, len(_launcherModeNames))
	copy(strs, _launcherModeNames)
	return strs
}

// IsAlauncherMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i launcherMode) IsAlauncherMode() bool {
	for _, v := range _launcherModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for launcherMode
func (i launcherMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for launcherMode
func (i *launcherMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("launcherMode should be a string, got %s", data)
	}

	var err error
	*i, err = launcherModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for launcherMode
func (i launcherMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for launcherMode
func (i *launcherMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = launcherModeString(string(text))
	return err
}

const _settingsActionGroupName = "keyboard_layoutvideo_qualitytls_modedisplay_rotationusb_emulationusb_devicesauto_updatedeveloper_modejigglerlocal_authmqtt_savemqtt_test"

var _settingsActionGroupIndex = [...]uint8{0, 15, 28, 36, 52, 65, 76, 87, 101, 108, 118, 127, 136}

const _settingsActionGroupLowerName = "keyboard_layoutvideo_qualitytls_modedisplay_rotationusb_emulationusb_devicesauto_updatedeveloper_modejigglerlocal_authmqtt_savemqtt_test"

func (i settingsActionGroup) String() string {
	if i >= settingsActionGroup(len(_settingsActionGroupIndex)-1) {
		return fmt.Sprintf("settingsActionGroup(%d)", i)
	}
	return _settingsActionGroupName[_settingsActionGroupIndex[i]:_settingsActionGroupIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _settingsActionGroupNoOp() {
	var x [1]struct{}
	_ = x[settingsGroupKeyboardLayout-(0)]
	_ = x[settingsGroupVideoQuality-(1)]
	_ = x[settingsGroupTLSMode-(2)]
	_ = x[settingsGroupDisplayRotate-(3)]
	_ = x[settingsGroupUSBEmulation-(4)]
	_ = x[settingsGroupUSBDevices-(5)]
	_ = x[settingsGroupAutoUpdate-(6)]
	_ = x[settingsGroupDeveloperMode-(7)]
	_ = x[settingsGroupJiggler-(8)]
	_ = x[settingsGroupLocalAuth-(9)]
	_ = x[settingsGroupMQTTSave-(10)]
	_ = x[settingsGroupMQTTTest-(11)]
}

var _settingsActionGroupValues = []settingsActionGroup{settingsGroupKeyboardLayout, settingsGroupVideoQuality, settingsGroupTLSMode, settingsGroupDisplayRotate, settingsGroupUSBEmulation, settingsGroupUSBDevices, settingsGroupAutoUpdate, settingsGroupDeveloperMode, settingsGroupJiggler, settingsGroupLocalAuth, settingsGroupMQTTSave, settingsGroupMQTTTest}

var _settingsActionGroupNameToValueMap = map[string]settingsActionGroup{
	_settingsActionGroupName[0:15]:         settingsGroupKeyboardLayout,
	_settingsActionGroupLowerName[0:15]:    settingsGroupKeyboardLayout,
	_settingsActionGroupName[15:28]:        settingsGroupVideoQuality,
	_settingsActionGroupLowerName[15:28]:   settingsGroupVideoQuality,
	_settingsActionGroupName[28:36]:        settingsGroupTLSMode,
	_settingsActionGroupLowerName[28:36]:   settingsGroupTLSMode,
	_settingsActionGroupName[36:52]:        settingsGroupDisplayRotate,
	_settingsActionGroupLowerName[36:52]:   settingsGroupDisplayRotate,
	_settingsActionGroupName[52:65]:        settingsGroupUSBEmulation,
	_settingsActionGroupLowerName[52:65]:   settingsGroupUSBEmulation,
	_settingsActionGroupName[65:76]:        settingsGroupUSBDevices,
	_settingsActionGroupLowerName[65:76]:   settingsGroupUSBDevices,
	_settingsActionGroupName[76:87]:        settingsGroupAutoUpdate,
	_settingsActionGroupLowerName[76:87]:   settingsGroupAutoUpdate,
	_settingsActionGroupName[87:101]:       settingsGroupDeveloperMode,
	_settingsActionGroupLowerName[87:101]:  settingsGroupDeveloperMode,
	_settingsActionGroupName[101:108]:      settingsGroupJiggler,
	_settingsActionGroupLowerName[101:108]: settingsGroupJiggler,
	_settingsActionGroupName[108:118]:      settingsGroupLocalAuth,
	_settingsActionGroupLowerName[108:118]: settingsGroupLocalAuth,
	_settingsActionGroupName[118:127]:      settingsGroupMQTTSave,
	_settingsActionGroupLowerName[118:127]: settingsGroupMQTTSave,
	_settingsActionGroupName[127:136]:      settingsGroupMQTTTest,
	_settingsActionGroupLowerName[127:136]: settingsGroupMQTTTest,
}

var _settingsActionGroupNames = []string{
	_settingsActionGroupName[0:15],
	_settingsActionGroupName[15:28],
	_settingsActionGroupName[28:36],
	_settingsActionGroupName[36:52],
	_settingsActionGroupName[52:65],
	_settingsActionGroupName[65:76],
	_settingsActionGroupName[76:87],
	_settingsActionGroupName[87:101],
	_settingsActionGroupName[101:108],
	_settingsActionGroupName[108:118],
	_settingsActionGroupName[118:127],
	_settingsActionGroupName[127:136],
}

// settingsActionGroupString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func settingsActionGroupString(s string) (settingsActionGroup, error) {
	if val, ok := _settingsActionGroupNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _settingsActionGroupNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to settingsActionGroup values", s)
}

// settingsActionGroupValues returns all values of the enum
func settingsActionGroupValues() []settingsActionGroup {
	return _settingsActionGroupValues
}

// settingsActionGroupStrings returns a slice of all String values of the enum
func settingsActionGroupStrings() []string {
	strs := make([]string, len(_settingsActionGroupNames))
	copy(strs, _settingsActionGroupNames)
	return strs
}

// IsAsettingsActionGroup returns "true" if the value is listed in the enum definition. "false" otherwise
func (i settingsActionGroup) IsAsettingsActionGroup() bool {
	for _, v := range _settingsActionGroupValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for settingsActionGroup
func (i settingsActionGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for settingsActionGroup
func (i *settingsActionGroup) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("settingsActionGroup should be a string, got %s", data)
	}

	var err error
	*i, err = settingsActionGroupString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for settingsActionGroup
func (i settingsActionGroup) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for settingsActionGroup
func (i *settingsActionGroup) UnmarshalText(text []byte) error {
	var err error
	*i, err = settingsActionGroupString(string(text))
	return err
}

const _mediaViewName = "homeurlstorageupload"

var _mediaViewIndex = [...]uint8{0, 4, 7, 14, 20}

const _mediaViewLowerName = "homeurlstorageupload"

func (i mediaView) String() string {
	if i >= mediaView(len(_mediaViewIndex)-1) {
		return fmt.Sprintf("mediaView(%d)", i)
	}
	return _mediaViewName[_mediaViewIndex[i]:_mediaViewIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _mediaViewNoOp() {
	var x [1]struct{}
	_ = x[mediaViewHome-(0)]
	_ = x[mediaViewURL-(1)]
	_ = x[mediaViewStorage-(2)]
	_ = x[mediaViewUpload-(3)]
}

var _mediaViewValues = []mediaView{mediaViewHome, mediaViewURL, mediaViewStorage, mediaViewUpload}

var _mediaViewNameToValueMap = map[string]mediaView{
	_mediaViewName[0:4]:        mediaViewHome,
	_mediaViewLowerName[0:4]:   mediaViewHome,
	_mediaViewName[4:7]:        mediaViewURL,
	_mediaViewLowerName[4:7]:   mediaViewURL,
	_mediaViewName[7:14]:       mediaViewStorage,
	_mediaViewLowerName[7:14]:  mediaViewStorage,
	_mediaViewName[14:20]:      mediaViewUpload,
	_mediaViewLowerName[14:20]: mediaViewUpload,
}

var _mediaViewNames = []string{
	_mediaViewName[0:4],
	_mediaViewName[4:7],
	_mediaViewName[7:14],
	_mediaViewName[14:20],
}

// mediaViewString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func mediaViewString(s string) (mediaView, error) {
	if val, ok := _mediaViewNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _mediaViewNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to mediaView values", s)
}

// mediaViewValues returns all values of the enum
func mediaViewValues() []mediaView {
	return _mediaViewValues
}

// mediaViewStrings returns a slice of all String values of the enum
func mediaViewStrings() []string {
	strs := make([]string, len(_mediaViewNames))
	copy(strs, _mediaViewNames)
	return strs
}

// IsAmediaView returns "true" if the value is listed in the enum definition. "false" otherwise
func (i mediaView) IsAmediaView() bool {
	for _, v := range _mediaViewValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for mediaView
func (i mediaView) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for mediaView
func (i *mediaView) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("mediaView should be a string, got %s", data)
	}

	var err error
	*i, err = mediaViewString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for mediaView
func (i mediaView) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for mediaView
func (i *mediaView) UnmarshalText(text []byte) error {
	var err error
	*i, err = mediaViewString(string(text))
	return err
}
