// Code generated by "enumer -type=launcherMode,settingsActionGroup,mediaView -linecomment -json -text -output app_enums.go"; DO NOT EDIT.

package app

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _launcherModeName = "browsepassword"

var _launcherModeIndex = [...]uint8{0, 6, 14}

const _launcherModeLowerName = "browsepassword"

func (i launcherMode) String() string {
	if i >= launcherMode(len(_launcherModeIndex)-1) {
		return fmt.Sprintf("launcherMode(%d)", i)
	}
	return _launcherModeName[_launcherModeIndex[i]:_launcherModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _launcherModeNoOp() {
	var x [1]struct{}
	_ = x[launcherModeBrowse-(0)]
	_ = x[launcherModePassword-(1)]
}

var _launcherModeValues = []launcherMode{launcherModeBrowse, launcherModePassword}

var _launcherModeNameToValueMap = map[string]launcherMode{
	_launcherModeName[0:6]:       launcherModeBrowse,
	_launcherModeLowerName[0:6]:  launcherModeBrowse,
	_launcherModeName[6:14]:      launcherModePassword,
	_launcherModeLowerName[6:14]: launcherModePassword,
}

var _launcherModeNames = []string{
	_launcherModeName[0:6],
	_launcherModeName[6:14],
}

// launcherModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func launcherModeString(s string) (launcherMode, error) {
	if val, ok := _launcherModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _launcherModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to launcherMode values", s)
}

// launcherModeValues returns all values of the enum
func launcherModeValues() []launcherMode {
	return _launcherModeValues
}

// launcherModeStrings returns a slice of all String values of the enum
func launcherModeStrings() []string {
	strs := make([]string, len(_launcherModeNames))
	copy(strs, _launcherModeNames)
	return strs
}

// IsAlauncherMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i launcherMode) IsAlauncherMode() bool {
	for _, v := range _launcherModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for launcherMode
func (i launcherMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for launcherMode
func (i *launcherMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("launcherMode should be a string, got %s", data)
	}

	var err error
	*i, err = launcherModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for launcherMode
func (i launcherMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for launcherMode
func (i *launcherMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = launcherModeString(string(text))
	return err
}

const _settingsActionGroupName = "keyboard_layoutvideo_qualityvideo_codecvideo_edidtls_modedisplay_rotationbacklightvideo_sleepusb_emulationusb_devicesauto_updateupdate_statusdeveloper_modedev_channelloopback_onlyssh_keynetwork_savemacros_savejigglerlocal_authmqtt_savemqtt_testupdate_installfactory_resetnetwork_refreshnetwork_renew_dhcpusb_network_save"

var _settingsActionGroupIndex = [...]uint16{0, 15, 28, 39, 49, 57, 73, 82, 93, 106, 117, 128, 141, 155, 166, 179, 186, 198, 209, 216, 226, 235, 244, 258, 271, 286, 304, 320}

const _settingsActionGroupLowerName = "keyboard_layoutvideo_qualityvideo_codecvideo_edidtls_modedisplay_rotationbacklightvideo_sleepusb_emulationusb_devicesauto_updateupdate_statusdeveloper_modedev_channelloopback_onlyssh_keynetwork_savemacros_savejigglerlocal_authmqtt_savemqtt_testupdate_installfactory_resetnetwork_refreshnetwork_renew_dhcpusb_network_save"

func (i settingsActionGroup) String() string {
	if i >= settingsActionGroup(len(_settingsActionGroupIndex)-1) {
		return fmt.Sprintf("settingsActionGroup(%d)", i)
	}
	return _settingsActionGroupName[_settingsActionGroupIndex[i]:_settingsActionGroupIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _settingsActionGroupNoOp() {
	var x [1]struct{}
	_ = x[settingsGroupKeyboardLayout-(0)]
	_ = x[settingsGroupVideoQuality-(1)]
	_ = x[settingsGroupVideoCodec-(2)]
	_ = x[settingsGroupVideoEDID-(3)]
	_ = x[settingsGroupTLSMode-(4)]
	_ = x[settingsGroupDisplayRotate-(5)]
	_ = x[settingsGroupBacklight-(6)]
	_ = x[settingsGroupVideoSleep-(7)]
	_ = x[settingsGroupUSBEmulation-(8)]
	_ = x[settingsGroupUSBDevices-(9)]
	_ = x[settingsGroupAutoUpdate-(10)]
	_ = x[settingsGroupUpdateStatus-(11)]
	_ = x[settingsGroupDeveloperMode-(12)]
	_ = x[settingsGroupDevChannel-(13)]
	_ = x[settingsGroupLoopbackOnly-(14)]
	_ = x[settingsGroupSSHKey-(15)]
	_ = x[settingsGroupNetworkSave-(16)]
	_ = x[settingsGroupMacrosSave-(17)]
	_ = x[settingsGroupJiggler-(18)]
	_ = x[settingsGroupLocalAuth-(19)]
	_ = x[settingsGroupMQTTSave-(20)]
	_ = x[settingsGroupMQTTTest-(21)]
	_ = x[settingsGroupUpdateInstall-(22)]
	_ = x[settingsGroupFactoryReset-(23)]
	_ = x[settingsGroupNetworkRefresh-(24)]
	_ = x[settingsGroupNetworkRenew-(25)]
	_ = x[settingsGroupUSBNetworkSave-(26)]
}

var _settingsActionGroupValues = []settingsActionGroup{settingsGroupKeyboardLayout, settingsGroupVideoQuality, settingsGroupVideoCodec, settingsGroupVideoEDID, settingsGroupTLSMode, settingsGroupDisplayRotate, settingsGroupBacklight, settingsGroupVideoSleep, settingsGroupUSBEmulation, settingsGroupUSBDevices, settingsGroupAutoUpdate, settingsGroupUpdateStatus, settingsGroupDeveloperMode, settingsGroupDevChannel, settingsGroupLoopbackOnly, settingsGroupSSHKey, settingsGroupNetworkSave, settingsGroupMacrosSave, settingsGroupJiggler, settingsGroupLocalAuth, settingsGroupMQTTSave, settingsGroupMQTTTest, settingsGroupUpdateInstall, settingsGroupFactoryReset, settingsGroupNetworkRefresh, settingsGroupNetworkRenew, settingsGroupUSBNetworkSave}

var _settingsActionGroupNameToValueMap = map[string]settingsActionGroup{
	_settingsActionGroupName[0:15]:         settingsGroupKeyboardLayout,
	_settingsActionGroupLowerName[0:15]:    settingsGroupKeyboardLayout,
	_settingsActionGroupName[15:28]:        settingsGroupVideoQuality,
	_settingsActionGroupLowerName[15:28]:   settingsGroupVideoQuality,
	_settingsActionGroupName[28:39]:        settingsGroupVideoCodec,
	_settingsActionGroupLowerName[28:39]:   settingsGroupVideoCodec,
	_settingsActionGroupName[39:49]:        settingsGroupVideoEDID,
	_settingsActionGroupLowerName[39:49]:   settingsGroupVideoEDID,
	_settingsActionGroupName[49:57]:        settingsGroupTLSMode,
	_settingsActionGroupLowerName[49:57]:   settingsGroupTLSMode,
	_settingsActionGroupName[57:73]:        settingsGroupDisplayRotate,
	_settingsActionGroupLowerName[57:73]:   settingsGroupDisplayRotate,
	_settingsActionGroupName[73:82]:        settingsGroupBacklight,
	_settingsActionGroupLowerName[73:82]:   settingsGroupBacklight,
	_settingsActionGroupName[82:93]:        settingsGroupVideoSleep,
	_settingsActionGroupLowerName[82:93]:   settingsGroupVideoSleep,
	_settingsActionGroupName[93:106]:       settingsGroupUSBEmulation,
	_settingsActionGroupLowerName[93:106]:  settingsGroupUSBEmulation,
	_settingsActionGroupName[106:117]:      settingsGroupUSBDevices,
	_settingsActionGroupLowerName[106:117]: settingsGroupUSBDevices,
	_settingsActionGroupName[117:128]:      settingsGroupAutoUpdate,
	_settingsActionGroupLowerName[117:128]: settingsGroupAutoUpdate,
	_settingsActionGroupName[128:141]:      settingsGroupUpdateStatus,
	_settingsActionGroupLowerName[128:141]: settingsGroupUpdateStatus,
	_settingsActionGroupName[141:155]:      settingsGroupDeveloperMode,
	_settingsActionGroupLowerName[141:155]: settingsGroupDeveloperMode,
	_settingsActionGroupName[155:166]:      settingsGroupDevChannel,
	_settingsActionGroupLowerName[155:166]: settingsGroupDevChannel,
	_settingsActionGroupName[166:179]:      settingsGroupLoopbackOnly,
	_settingsActionGroupLowerName[166:179]: settingsGroupLoopbackOnly,
	_settingsActionGroupName[179:186]:      settingsGroupSSHKey,
	_settingsActionGroupLowerName[179:186]: settingsGroupSSHKey,
	_settingsActionGroupName[186:198]:      settingsGroupNetworkSave,
	_settingsActionGroupLowerName[186:198]: settingsGroupNetworkSave,
	_settingsActionGroupName[198:209]:      settingsGroupMacrosSave,
	_settingsActionGroupLowerName[198:209]: settingsGroupMacrosSave,
	_settingsActionGroupName[209:216]:      settingsGroupJiggler,
	_settingsActionGroupLowerName[209:216]: settingsGroupJiggler,
	_settingsActionGroupName[216:226]:      settingsGroupLocalAuth,
	_settingsActionGroupLowerName[216:226]: settingsGroupLocalAuth,
	_settingsActionGroupName[226:235]:      settingsGroupMQTTSave,
	_settingsActionGroupLowerName[226:235]: settingsGroupMQTTSave,
	_settingsActionGroupName[235:244]:      settingsGroupMQTTTest,
	_settingsActionGroupLowerName[235:244]: settingsGroupMQTTTest,
	_settingsActionGroupName[244:258]:      settingsGroupUpdateInstall,
	_settingsActionGroupLowerName[244:258]: settingsGroupUpdateInstall,
	_settingsActionGroupName[258:271]:      settingsGroupFactoryReset,
	_settingsActionGroupLowerName[258:271]: settingsGroupFactoryReset,
	_settingsActionGroupName[271:286]:      settingsGroupNetworkRefresh,
	_settingsActionGroupLowerName[271:286]: settingsGroupNetworkRefresh,
	_settingsActionGroupName[286:304]:      settingsGroupNetworkRenew,
	_settingsActionGroupLowerName[286:304]: settingsGroupNetworkRenew,
	_settingsActionGroupName[304:320]:      settingsGroupUSBNetworkSave,
	_settingsActionGroupLowerName[304:320]: settingsGroupUSBNetworkSave,
}

var _settingsActionGroupNames = []string{
	_settingsActionGroupName[0:15],
	_settingsActionGroupName[15:28],
	_settingsActionGroupName[28:39],
	_settingsActionGroupName[39:49],
	_settingsActionGroupName[49:57],
	_settingsActionGroupName[57:73],
	_settingsActionGroupName[73:82],
	_settingsActionGroupName[82:93],
	_settingsActionGroupName[93:106],
	_settingsActionGroupName[106:117],
	_settingsActionGroupName[117:128],
	_settingsActionGroupName[128:141],
	_settingsActionGroupName[141:155],
	_settingsActionGroupName[155:166],
	_settingsActionGroupName[166:179],
	_settingsActionGroupName[179:186],
	_settingsActionGroupName[186:198],
	_settingsActionGroupName[198:209],
	_settingsActionGroupName[209:216],
	_settingsActionGroupName[216:226],
	_settingsActionGroupName[226:235],
	_settingsActionGroupName[235:244],
	_settingsActionGroupName[244:258],
	_settingsActionGroupName[258:271],
	_settingsActionGroupName[271:286],
	_settingsActionGroupName[286:304],
	_settingsActionGroupName[304:320],
}

// settingsActionGroupString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func settingsActionGroupString(s string) (settingsActionGroup, error) {
	if val, ok := _settingsActionGroupNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _settingsActionGroupNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to settingsActionGroup values", s)
}

// settingsActionGroupValues returns all values of the enum
func settingsActionGroupValues() []settingsActionGroup {
	return _settingsActionGroupValues
}

// settingsActionGroupStrings returns a slice of all String values of the enum
func settingsActionGroupStrings() []string {
	strs := make([]string, len(_settingsActionGroupNames))
	copy(strs, _settingsActionGroupNames)
	return strs
}

// IsAsettingsActionGroup returns "true" if the value is listed in the enum definition. "false" otherwise
func (i settingsActionGroup) IsAsettingsActionGroup() bool {
	for _, v := range _settingsActionGroupValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for settingsActionGroup
func (i settingsActionGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for settingsActionGroup
func (i *settingsActionGroup) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("settingsActionGroup should be a string, got %s", data)
	}

	var err error
	*i, err = settingsActionGroupString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for settingsActionGroup
func (i settingsActionGroup) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for settingsActionGroup
func (i *settingsActionGroup) UnmarshalText(text []byte) error {
	var err error
	*i, err = settingsActionGroupString(string(text))
	return err
}

const _mediaViewName = "homeurlstorageupload"

var _mediaViewIndex = [...]uint8{0, 4, 7, 14, 20}

const _mediaViewLowerName = "homeurlstorageupload"

func (i mediaView) String() string {
	if i >= mediaView(len(_mediaViewIndex)-1) {
		return fmt.Sprintf("mediaView(%d)", i)
	}
	return _mediaViewName[_mediaViewIndex[i]:_mediaViewIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _mediaViewNoOp() {
	var x [1]struct{}
	_ = x[mediaViewHome-(0)]
	_ = x[mediaViewURL-(1)]
	_ = x[mediaViewStorage-(2)]
	_ = x[mediaViewUpload-(3)]
}

var _mediaViewValues = []mediaView{mediaViewHome, mediaViewURL, mediaViewStorage, mediaViewUpload}

var _mediaViewNameToValueMap = map[string]mediaView{
	_mediaViewName[0:4]:        mediaViewHome,
	_mediaViewLowerName[0:4]:   mediaViewHome,
	_mediaViewName[4:7]:        mediaViewURL,
	_mediaViewLowerName[4:7]:   mediaViewURL,
	_mediaViewName[7:14]:       mediaViewStorage,
	_mediaViewLowerName[7:14]:  mediaViewStorage,
	_mediaViewName[14:20]:      mediaViewUpload,
	_mediaViewLowerName[14:20]: mediaViewUpload,
}

var _mediaViewNames = []string{
	_mediaViewName[0:4],
	_mediaViewName[4:7],
	_mediaViewName[7:14],
	_mediaViewName[14:20],
}

// mediaViewString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func mediaViewString(s string) (mediaView, error) {
	if val, ok := _mediaViewNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _mediaViewNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to mediaView values", s)
}

// mediaViewValues returns all values of the enum
func mediaViewValues() []mediaView {
	return _mediaViewValues
}

// mediaViewStrings returns a slice of all String values of the enum
func mediaViewStrings() []string {
	strs := make([]string, len(_mediaViewNames))
	copy(strs, _mediaViewNames)
	return strs
}

// IsAmediaView returns "true" if the value is listed in the enum definition. "false" otherwise
func (i mediaView) IsAmediaView() bool {
	for _, v := range _mediaViewValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for mediaView
func (i mediaView) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for mediaView
func (i *mediaView) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("mediaView should be a string, got %s", data)
	}

	var err error
	*i, err = mediaViewString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for mediaView
func (i mediaView) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for mediaView
func (i *mediaView) UnmarshalText(text []byte) error {
	var err error
	*i, err = mediaViewString(string(text))
	return err
}
