// Code generated by "enumer -type=iconKind,settingsSection -linecomment -json -text -output chrome_enums.go"; DO NOT EDIT.

package app

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _iconKindName = "reconnectmousepastemediastatsminuspluspowersettingsfullscreenclose"

var _iconKindIndex = [...]uint8{0, 9, 14, 19, 24, 29, 34, 38, 43, 51, 61, 66}

const _iconKindLowerName = "reconnectmousepastemediastatsminuspluspowersettingsfullscreenclose"

func (i iconKind) String() string {
	if i >= iconKind(len(_iconKindIndex)-1) {
		return fmt.Sprintf("iconKind(%d)", i)
	}
	return _iconKindName[_iconKindIndex[i]:_iconKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _iconKindNoOp() {
	var x [1]struct{}
	_ = x[iconReconnect-(0)]
	_ = x[iconMouse-(1)]
	_ = x[iconPaste-(2)]
	_ = x[iconMedia-(3)]
	_ = x[iconStats-(4)]
	_ = x[iconMinus-(5)]
	_ = x[iconPlus-(6)]
	_ = x[iconPower-(7)]
	_ = x[iconSettings-(8)]
	_ = x[iconFullscreen-(9)]
	_ = x[iconClose-(10)]
}

var _iconKindValues = []iconKind{iconReconnect, iconMouse, iconPaste, iconMedia, iconStats, iconMinus, iconPlus, iconPower, iconSettings, iconFullscreen, iconClose}

var _iconKindNameToValueMap = map[string]iconKind{
	_iconKindName[0:9]:        iconReconnect,
	_iconKindLowerName[0:9]:   iconReconnect,
	_iconKindName[9:14]:       iconMouse,
	_iconKindLowerName[9:14]:  iconMouse,
	_iconKindName[14:19]:      iconPaste,
	_iconKindLowerName[14:19]: iconPaste,
	_iconKindName[19:24]:      iconMedia,
	_iconKindLowerName[19:24]: iconMedia,
	_iconKindName[24:29]:      iconStats,
	_iconKindLowerName[24:29]: iconStats,
	_iconKindName[29:34]:      iconMinus,
	_iconKindLowerName[29:34]: iconMinus,
	_iconKindName[34:38]:      iconPlus,
	_iconKindLowerName[34:38]: iconPlus,
	_iconKindName[38:43]:      iconPower,
	_iconKindLowerName[38:43]: iconPower,
	_iconKindName[43:51]:      iconSettings,
	_iconKindLowerName[43:51]: iconSettings,
	_iconKindName[51:61]:      iconFullscreen,
	_iconKindLowerName[51:61]: iconFullscreen,
	_iconKindName[61:66]:      iconClose,
	_iconKindLowerName[61:66]: iconClose,
}

var _iconKindNames = []string{
	_iconKindName[0:9],
	_iconKindName[9:14],
	_iconKindName[14:19],
	_iconKindName[19:24],
	_iconKindName[24:29],
	_iconKindName[29:34],
	_iconKindName[34:38],
	_iconKindName[38:43],
	_iconKindName[43:51],
	_iconKindName[51:61],
	_iconKindName[61:66],
}

// iconKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func iconKindString(s string) (iconKind, error) {
	if val, ok := _iconKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _iconKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to iconKind values", s)
}

// iconKindValues returns all values of the enum
func iconKindValues() []iconKind {
	return _iconKindValues
}

// iconKindStrings returns a slice of all String values of the enum
func iconKindStrings() []string {
	strs := make([]string, len(_iconKindNames))
	copy(strs, _iconKindNames)
	return strs
}

// IsAiconKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i iconKind) IsAiconKind() bool {
	for _, v := range _iconKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for iconKind
func (i iconKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for iconKind
func (i *iconKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("iconKind should be a string, got %s", data)
	}

	var err error
	*i, err = iconKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for iconKind
func (i iconKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for iconKind
func (i *iconKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = iconKindString(string(text))
	return err
}

const _settingsSectionName = "generalmousekeyboardvideohardwareaccessappearancemacrosnetworkmqttadvanced"

var _settingsSectionIndex = [...]uint8{0, 7, 12, 20, 25, 33, 39, 49, 55, 62, 66, 74}

const _settingsSectionLowerName = "generalmousekeyboardvideohardwareaccessappearancemacrosnetworkmqttadvanced"

func (i settingsSection) String() string {
	if i >= settingsSection(len(_settingsSectionIndex)-1) {
		return fmt.Sprintf("settingsSection(%d)", i)
	}
	return _settingsSectionName[_settingsSectionIndex[i]:_settingsSectionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _settingsSectionNoOp() {
	var x [1]struct{}
	_ = x[sectionGeneral-(0)]
	_ = x[sectionMouse-(1)]
	_ = x[sectionKeyboard-(2)]
	_ = x[sectionVideo-(3)]
	_ = x[sectionHardware-(4)]
	_ = x[sectionAccess-(5)]
	_ = x[sectionAppearance-(6)]
	_ = x[sectionMacros-(7)]
	_ = x[sectionNetwork-(8)]
	_ = x[sectionMQTT-(9)]
	_ = x[sectionAdvanced-(10)]
}

var _settingsSectionValues = []settingsSection{sectionGeneral, sectionMouse, sectionKeyboard, sectionVideo, sectionHardware, sectionAccess, sectionAppearance, sectionMacros, sectionNetwork, sectionMQTT, sectionAdvanced}

var _settingsSectionNameToValueMap = map[string]settingsSection{
	_settingsSectionName[0:7]:        sectionGeneral,
	_settingsSectionLowerName[0:7]:   sectionGeneral,
	_settingsSectionName[7:12]:       sectionMouse,
	_settingsSectionLowerName[7:12]:  sectionMouse,
	_settingsSectionName[12:20]:      sectionKeyboard,
	_settingsSectionLowerName[12:20]: sectionKeyboard,
	_settingsSectionName[20:25]:      sectionVideo,
	_settingsSectionLowerName[20:25]: sectionVideo,
	_settingsSectionName[25:33]:      sectionHardware,
	_settingsSectionLowerName[25:33]: sectionHardware,
	_settingsSectionName[33:39]:      sectionAccess,
	_settingsSectionLowerName[33:39]: sectionAccess,
	_settingsSectionName[39:49]:      sectionAppearance,
	_settingsSectionLowerName[39:49]: sectionAppearance,
	_settingsSectionName[49:55]:      sectionMacros,
	_settingsSectionLowerName[49:55]: sectionMacros,
	_settingsSectionName[55:62]:      sectionNetwork,
	_settingsSectionLowerName[55:62]: sectionNetwork,
	_settingsSectionName[62:66]:      sectionMQTT,
	_settingsSectionLowerName[62:66]: sectionMQTT,
	_settingsSectionName[66:74]:      sectionAdvanced,
	_settingsSectionLowerName[66:74]: sectionAdvanced,
}

var _settingsSectionNames = []string{
	_settingsSectionName[0:7],
	_settingsSectionName[7:12],
	_settingsSectionName[12:20],
	_settingsSectionName[20:25],
	_settingsSectionName[25:33],
	_settingsSectionName[33:39],
	_settingsSectionName[39:49],
	_settingsSectionName[49:55],
	_settingsSectionName[55:62],
	_settingsSectionName[62:66],
	_settingsSectionName[66:74],
}

// settingsSectionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func settingsSectionString(s string) (settingsSection, error) {
	if val, ok := _settingsSectionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _settingsSectionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to settingsSection values", s)
}

// settingsSectionValues returns all values of the enum
func settingsSectionValues() []settingsSection {
	return _settingsSectionValues
}

// settingsSectionStrings returns a slice of all String values of the enum
func settingsSectionStrings() []string {
	strs := make([]string, len(_settingsSectionNames))
	copy(strs, _settingsSectionNames)
	return strs
}

// IsAsettingsSection returns "true" if the value is listed in the enum definition. "false" otherwise
func (i settingsSection) IsAsettingsSection() bool {
	for _, v := range _settingsSectionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for settingsSection
func (i settingsSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for settingsSection
func (i *settingsSection) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("settingsSection should be a string, got %s", data)
	}

	var err error
	*i, err = settingsSectionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for settingsSection
func (i settingsSection) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for settingsSection
func (i *settingsSection) UnmarshalText(text []byte) error {
	var err error
	*i, err = settingsSectionString(string(text))
	return err
}
