// Code generated by "enumer -type=Theme,ChromeAnchor,ChromeLayout,ScrollThrottle -linecomment -json -text -output prefs_enums.go"; DO NOT EDIT.

package app

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ThemeName = "unknownsystemdarklight"

var _ThemeIndex = [...]uint8{0, 7, 13, 17, 22}

const _ThemeLowerName = "unknownsystemdarklight"

func (i Theme) String() string {
	if i >= Theme(len(_ThemeIndex)-1) {
		return fmt.Sprintf("Theme(%d)", i)
	}
	return _ThemeName[_ThemeIndex[i]:_ThemeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ThemeNoOp() {
	var x [1]struct{}
	_ = x[themeUnknown-(0)]
	_ = x[themeSystem-(1)]
	_ = x[themeDark-(2)]
	_ = x[themeLight-(3)]
}

var _ThemeValues = []Theme{themeUnknown, themeSystem, themeDark, themeLight}

var _ThemeNameToValueMap = map[string]Theme{
	_ThemeName[0:7]:        themeUnknown,
	_ThemeLowerName[0:7]:   themeUnknown,
	_ThemeName[7:13]:       themeSystem,
	_ThemeLowerName[7:13]:  themeSystem,
	_ThemeName[13:17]:      themeDark,
	_ThemeLowerName[13:17]: themeDark,
	_ThemeName[17:22]:      themeLight,
	_ThemeLowerName[17:22]: themeLight,
}

var _ThemeNames = []string{
	_ThemeName[0:7],
	_ThemeName[7:13],
	_ThemeName[13:17],
	_ThemeName[17:22],
}

// ThemeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ThemeString(s string) (Theme, error) {
	if val, ok := _ThemeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ThemeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Theme values", s)
}

// ThemeValues returns all values of the enum
func ThemeValues() []Theme {
	return _ThemeValues
}

// ThemeStrings returns a slice of all String values of the enum
func ThemeStrings() []string {
	strs := make([]string, len(_ThemeNames))
	copy(strs, _ThemeNames)
	return strs
}

// IsATheme returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Theme) IsATheme() bool {
	for _, v := range _ThemeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Theme
func (i Theme) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Theme
func (i *Theme) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Theme should be a string, got %s", data)
	}

	var err error
	*i, err = ThemeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Theme
func (i Theme) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Theme
func (i *Theme) UnmarshalText(text []byte) error {
	var err error
	*i, err = ThemeString(string(text))
	return err
}

const _ChromeAnchorName = "unknowntop_lefttop_centertop_rightleft_centerright_centerbottom_leftbottom_centerbottom_right"

var _ChromeAnchorIndex = [...]uint8{0, 7, 15, 25, 34, 45, 57, 68, 81, 93}

const _ChromeAnchorLowerName = "unknowntop_lefttop_centertop_rightleft_centerright_centerbottom_leftbottom_centerbottom_right"

func (i ChromeAnchor) String() string {
	if i >= ChromeAnchor(len(_ChromeAnchorIndex)-1) {
		return fmt.Sprintf("ChromeAnchor(%d)", i)
	}
	return _ChromeAnchorName[_ChromeAnchorIndex[i]:_ChromeAnchorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ChromeAnchorNoOp() {
	var x [1]struct{}
	_ = x[chromeAnchorUnknown-(0)]
	_ = x[chromeAnchorTopLeft-(1)]
	_ = x[chromeAnchorTopCenter-(2)]
	_ = x[chromeAnchorTopRight-(3)]
	_ = x[chromeAnchorLeftCenter-(4)]
	_ = x[chromeAnchorRightCenter-(5)]
	_ = x[chromeAnchorBottomLeft-(6)]
	_ = x[chromeAnchorBottomCenter-(7)]
	_ = x[chromeAnchorBottomRight-(8)]
}

var _ChromeAnchorValues = []ChromeAnchor{chromeAnchorUnknown, chromeAnchorTopLeft, chromeAnchorTopCenter, chromeAnchorTopRight, chromeAnchorLeftCenter, chromeAnchorRightCenter, chromeAnchorBottomLeft, chromeAnchorBottomCenter, chromeAnchorBottomRight}

var _ChromeAnchorNameToValueMap = map[string]ChromeAnchor{
	_ChromeAnchorName[0:7]:        chromeAnchorUnknown,
	_ChromeAnchorLowerName[0:7]:   chromeAnchorUnknown,
	_ChromeAnchorName[7:15]:       chromeAnchorTopLeft,
	_ChromeAnchorLowerName[7:15]:  chromeAnchorTopLeft,
	_ChromeAnchorName[15:25]:      chromeAnchorTopCenter,
	_ChromeAnchorLowerName[15:25]: chromeAnchorTopCenter,
	_ChromeAnchorName[25:34]:      chromeAnchorTopRight,
	_ChromeAnchorLowerName[25:34]: chromeAnchorTopRight,
	_ChromeAnchorName[34:45]:      chromeAnchorLeftCenter,
	_ChromeAnchorLowerName[34:45]: chromeAnchorLeftCenter,
	_ChromeAnchorName[45:57]:      chromeAnchorRightCenter,
	_ChromeAnchorLowerName[45:57]: chromeAnchorRightCenter,
	_ChromeAnchorName[57:68]:      chromeAnchorBottomLeft,
	_ChromeAnchorLowerName[57:68]: chromeAnchorBottomLeft,
	_ChromeAnchorName[68:81]:      chromeAnchorBottomCenter,
	_ChromeAnchorLowerName[68:81]: chromeAnchorBottomCenter,
	_ChromeAnchorName[81:93]:      chromeAnchorBottomRight,
	_ChromeAnchorLowerName[81:93]: chromeAnchorBottomRight,
}

var _ChromeAnchorNames = []string{
	_ChromeAnchorName[0:7],
	_ChromeAnchorName[7:15],
	_ChromeAnchorName[15:25],
	_ChromeAnchorName[25:34],
	_ChromeAnchorName[34:45],
	_ChromeAnchorName[45:57],
	_ChromeAnchorName[57:68],
	_ChromeAnchorName[68:81],
	_ChromeAnchorName[81:93],
}

// ChromeAnchorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChromeAnchorString(s string) (ChromeAnchor, error) {
	if val, ok := _ChromeAnchorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ChromeAnchorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChromeAnchor values", s)
}

// ChromeAnchorValues returns all values of the enum
func ChromeAnchorValues() []ChromeAnchor {
	return _ChromeAnchorValues
}

// ChromeAnchorStrings returns a slice of all String values of the enum
func ChromeAnchorStrings() []string {
	strs := make([]string, len(_ChromeAnchorNames))
	copy(strs, _ChromeAnchorNames)
	return strs
}

// IsAChromeAnchor returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChromeAnchor) IsAChromeAnchor() bool {
	for _, v := range _ChromeAnchorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ChromeAnchor
func (i ChromeAnchor) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ChromeAnchor
func (i *ChromeAnchor) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ChromeAnchor should be a string, got %s", data)
	}

	var err error
	*i, err = ChromeAnchorString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ChromeAnchor
func (i ChromeAnchor) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ChromeAnchor
func (i *ChromeAnchor) UnmarshalText(text []byte) error {
	var err error
	*i, err = ChromeAnchorString(string(text))
	return err
}

const _ChromeLayoutName = "unknownhorizontalvertical"

var _ChromeLayoutIndex = [...]uint8{0, 7, 17, 25}

const _ChromeLayoutLowerName = "unknownhorizontalvertical"

func (i ChromeLayout) String() string {
	if i >= ChromeLayout(len(_ChromeLayoutIndex)-1) {
		return fmt.Sprintf("ChromeLayout(%d)", i)
	}
	return _ChromeLayoutName[_ChromeLayoutIndex[i]:_ChromeLayoutIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ChromeLayoutNoOp() {
	var x [1]struct{}
	_ = x[chromeLayoutUnknown-(0)]
	_ = x[chromeLayoutHorizontal-(1)]
	_ = x[chromeLayoutVertical-(2)]
}

var _ChromeLayoutValues = []ChromeLayout{chromeLayoutUnknown, chromeLayoutHorizontal, chromeLayoutVertical}

var _ChromeLayoutNameToValueMap = map[string]ChromeLayout{
	_ChromeLayoutName[0:7]:        chromeLayoutUnknown,
	_ChromeLayoutLowerName[0:7]:   chromeLayoutUnknown,
	_ChromeLayoutName[7:17]:       chromeLayoutHorizontal,
	_ChromeLayoutLowerName[7:17]:  chromeLayoutHorizontal,
	_ChromeLayoutName[17:25]:      chromeLayoutVertical,
	_ChromeLayoutLowerName[17:25]: chromeLayoutVertical,
}

var _ChromeLayoutNames = []string{
	_ChromeLayoutName[0:7],
	_ChromeLayoutName[7:17],
	_ChromeLayoutName[17:25],
}

// ChromeLayoutString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChromeLayoutString(s string) (ChromeLayout, error) {
	if val, ok := _ChromeLayoutNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ChromeLayoutNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChromeLayout values", s)
}

// ChromeLayoutValues returns all values of the enum
func ChromeLayoutValues() []ChromeLayout {
	return _ChromeLayoutValues
}

// ChromeLayoutStrings returns a slice of all String values of the enum
func ChromeLayoutStrings() []string {
	strs := make([]string, len(_ChromeLayoutNames))
	copy(strs, _ChromeLayoutNames)
	return strs
}

// IsAChromeLayout returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChromeLayout) IsAChromeLayout() bool {
	for _, v := range _ChromeLayoutValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ChromeLayout
func (i ChromeLayout) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ChromeLayout
func (i *ChromeLayout) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ChromeLayout should be a string, got %s", data)
	}

	var err error
	*i, err = ChromeLayoutString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ChromeLayout
func (i ChromeLayout) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ChromeLayout
func (i *ChromeLayout) UnmarshalText(text []byte) error {
	var err error
	*i, err = ChromeLayoutString(string(text))
	return err
}

const _ScrollThrottleName = "unknown0102550100"

var _ScrollThrottleIndex = [...]uint8{0, 7, 8, 10, 12, 14, 17}

const _ScrollThrottleLowerName = "unknown0102550100"

func (i ScrollThrottle) String() string {
	if i >= ScrollThrottle(len(_ScrollThrottleIndex)-1) {
		return fmt.Sprintf("ScrollThrottle(%d)", i)
	}
	return _ScrollThrottleName[_ScrollThrottleIndex[i]:_ScrollThrottleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ScrollThrottleNoOp() {
	var x [1]struct{}
	_ = x[scrollThrottleUnknown-(0)]
	_ = x[scrollThrottleOff-(1)]
	_ = x[scrollThrottle10ms-(2)]
	_ = x[scrollThrottle25ms-(3)]
	_ = x[scrollThrottle50ms-(4)]
	_ = x[scrollThrottle100ms-(5)]
}

var _ScrollThrottleValues = []ScrollThrottle{scrollThrottleUnknown, scrollThrottleOff, scrollThrottle10ms, scrollThrottle25ms, scrollThrottle50ms, scrollThrottle100ms}

var _ScrollThrottleNameToValueMap = map[string]ScrollThrottle{
	_ScrollThrottleName[0:7]:        scrollThrottleUnknown,
	_ScrollThrottleLowerName[0:7]:   scrollThrottleUnknown,
	_ScrollThrottleName[7:8]:        scrollThrottleOff,
	_ScrollThrottleLowerName[7:8]:   scrollThrottleOff,
	_ScrollThrottleName[8:10]:       scrollThrottle10ms,
	_ScrollThrottleLowerName[8:10]:  scrollThrottle10ms,
	_ScrollThrottleName[10:12]:      scrollThrottle25ms,
	_ScrollThrottleLowerName[10:12]: scrollThrottle25ms,
	_ScrollThrottleName[12:14]:      scrollThrottle50ms,
	_ScrollThrottleLowerName[12:14]: scrollThrottle50ms,
	_ScrollThrottleName[14:17]:      scrollThrottle100ms,
	_ScrollThrottleLowerName[14:17]: scrollThrottle100ms,
}

var _ScrollThrottleNames = []string{
	_ScrollThrottleName[0:7],
	_ScrollThrottleName[7:8],
	_ScrollThrottleName[8:10],
	_ScrollThrottleName[10:12],
	_ScrollThrottleName[12:14],
	_ScrollThrottleName[14:17],
}

// ScrollThrottleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ScrollThrottleString(s string) (ScrollThrottle, error) {
	if val, ok := _ScrollThrottleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ScrollThrottleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ScrollThrottle values", s)
}

// ScrollThrottleValues returns all values of the enum
func ScrollThrottleValues() []ScrollThrottle {
	return _ScrollThrottleValues
}

// ScrollThrottleStrings returns a slice of all String values of the enum
func ScrollThrottleStrings() []string {
	strs := make([]string, len(_ScrollThrottleNames))
	copy(strs, _ScrollThrottleNames)
	return strs
}

// IsAScrollThrottle returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ScrollThrottle) IsAScrollThrottle() bool {
	for _, v := range _ScrollThrottleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ScrollThrottle
func (i ScrollThrottle) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ScrollThrottle
func (i *ScrollThrottle) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ScrollThrottle should be a string, got %s", data)
	}

	var err error
	*i, err = ScrollThrottleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ScrollThrottle
func (i ScrollThrottle) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ScrollThrottle
func (i *ScrollThrottle) UnmarshalText(text []byte) error {
	var err error
	*i, err = ScrollThrottleString(string(text))
	return err
}
