// Code generated by "enumer -type=SignalingMode -linecomment -text -output client_enums.go"; DO NOT EDIT.

package client

import (
	"fmt"
	"strings"
)

const _SignalingModeName = "unknownlegacy_httpwebsocket"

var _SignalingModeIndex = [...]uint8{0, 7, 18, 27}

const _SignalingModeLowerName = "unknownlegacy_httpwebsocket"

func (i SignalingMode) String() string {
	if i >= SignalingMode(len(_SignalingModeIndex)-1) {
		return fmt.Sprintf("SignalingMode(%d)", i)
	}
	return _SignalingModeName[_SignalingModeIndex[i]:_SignalingModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SignalingModeNoOp() {
	var x [1]struct{}
	_ = x[SignalingModeUnknown-(0)]
	_ = x[SignalingModeLegacyHTTP-(1)]
	_ = x[SignalingModeWebSocket-(2)]
}

var _SignalingModeValues = []SignalingMode{SignalingModeUnknown, SignalingModeLegacyHTTP, SignalingModeWebSocket}

var _SignalingModeNameToValueMap = map[string]SignalingMode{
	_SignalingModeName[0:7]:        SignalingModeUnknown,
	_SignalingModeLowerName[0:7]:   SignalingModeUnknown,
	_SignalingModeName[7:18]:       SignalingModeLegacyHTTP,
	_SignalingModeLowerName[7:18]:  SignalingModeLegacyHTTP,
	_SignalingModeName[18:27]:      SignalingModeWebSocket,
	_SignalingModeLowerName[18:27]: SignalingModeWebSocket,
}

var _SignalingModeNames = []string{
	_SignalingModeName[0:7],
	_SignalingModeName[7:18],
	_SignalingModeName[18:27],
}

// SignalingModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SignalingModeString(s string) (SignalingMode, error) {
	if val, ok := _SignalingModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SignalingModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SignalingMode values", s)
}

// SignalingModeValues returns all values of the enum
func SignalingModeValues() []SignalingMode {
	return _SignalingModeValues
}

// SignalingModeStrings returns a slice of all String values of the enum
func SignalingModeStrings() []string {
	strs := make([]string, len(_SignalingModeNames))
	copy(strs, _SignalingModeNames)
	return strs
}

// IsASignalingMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SignalingMode) IsASignalingMode() bool {
	for _, v := range _SignalingModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for SignalingMode
func (i SignalingMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SignalingMode
func (i *SignalingMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = SignalingModeString(string(text))
	return err
}
