name: Reusable Go Test

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      goos:
        required: false
        type: string
        default: ""
      goarch:
        required: false
        type: string
        default: ""

jobs:
  test:
    name: Test
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up native environment
        uses: ./.github/actions/setup-native-env
        with:
          install-xvfb: "true"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        env:
          GOOS: ${{ inputs.goos }}
          GOARCH: ${{ inputs.goarch }}
        run: xvfb-run -a go test ./...

      - name: Run tests (non-Linux)
        if: runner.os != 'Linux'
        env:
          GOOS: ${{ inputs.goos }}
          GOARCH: ${{ inputs.goarch }}
        run: go test ./...
